/* Generated By:JavaCC: Do not edit this line. PhysicsConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PhysicsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTERO = 5;
  /** RegularExpression Id. */
  int PABRE = 6;
  /** RegularExpression Id. */
  int PCIERRA = 7;
  /** RegularExpression Id. */
  int MAS = 8;
  /** RegularExpression Id. */
  int ASTERISCO = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int POS = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int DOSP = 14;
  /** RegularExpression Id. */
  int COMA = 15;
  /** RegularExpression Id. */
  int DONE = 16;
  /** RegularExpression Id. */
  int ASIGNA = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int TO = 19;
  /** RegularExpression Id. */
  int START = 20;
  /** RegularExpression Id. */
  int END = 21;
  /** RegularExpression Id. */
  int IMPR = 22;
  /** RegularExpression Id. */
  int TPAR = 23;
  /** RegularExpression Id. */
  int MHOR = 24;
  /** RegularExpression Id. */
  int OBJ = 25;
  /** RegularExpression Id. */
  int OPLOG = 26;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int CADENA = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ENTERO>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "\"var\"",
    "\"pos\"",
    "\"if\"",
    "\"else\"",
    "\":\"",
    "\",\"",
    "\"done\"",
    "\"=\"",
    "\"for\"",
    "\"to\"",
    "\"|#physics_start\"",
    "\"#end\"",
    "\"imprimir\"",
    "\"tiro_parabolico\"",
    "\"mover_horizontal\"",
    "\"obj\"",
    "<OPLOG>",
    "<ID>",
    "<CADENA>",
  };

}
